import type { Booking, PricePackage, RouteItem, Vehicle } from "@/lib/types";

export const vehicles: Vehicle[] = [
  {
    id: 1,
    name: "VinFast VF7 Limousine",
    type: "SUV ĐIỆN LUXURY",
    seats: 5,
    plateNumber: "75A-12345",
    imageUrl: "/images/fleet/vf7.png",
    description: "Xe đời mới, đón tận nơi, điều hòa mát, ghế da cao cấp.",
    status: "active",
  },
  {
    id: 2,
    name: "Kia Carnival Royal",
    type: "MPV HẠNG SANG",
    seats: 7,
    plateNumber: "43A-67890",
    imageUrl: "/images/fleet/carnival.png",
    description: "Phù hợp gia đình, lịch đi linh hoạt, không ghép khách.",
    status: "active",
  },
  {
    id: 3,
    name: "Ford Transit 2024",
    type: "MINIBUS CAO CẤP",
    seats: 16,
    plateNumber: "92B-24680",
    imageUrl: "/images/fleet/transit.png",
    description: "Dành cho đoàn du lịch, công ty, gia đình đông người.",
    status: "active",
  },
];

export const routes: RouteItem[] = [
  { id: 1, from: "Huế", to: "Đà Nẵng", distanceKm: 100, duration: "2 giờ", status: "active" },
  { id: 2, from: "Đà Nẵng", to: "Hội An", distanceKm: 30, duration: "45 phút", status: "active" },
  { id: 3, from: "Huế", to: "Hội An", distanceKm: 130, duration: "2 giờ 45 phút", status: "active" },
];

export const pricePackages: PricePackage[] = [
  {
    id: 1,
    vehicleName: "Limousine 7 chỗ",
    routeName: "Huế → Đà Nẵng",
    type: "shared-seat",
    price: 200000,
    description: "Xe ghép theo chỗ, đưa đón tận nơi.",
    status: "active",
  },
  {
    id: 2,
    vehicleName: "Sedan 4 chỗ",
    routeName: "Huế → Đà Nẵng",
    type: "private-trip",
    price: 1200000,
    description: "Bao nguyên xe, chủ động thời gian.",
    status: "active",
  },
  {
    id: 3,
    vehicleName: "Limousine 7 chỗ",
    routeName: "Đà Nẵng → Hội An",
    type: "shared-seat",
    price: 120000,
    description: "Xe ghép tuyến ngắn, đi hằng ngày.",
    status: "active",
  },
  {
    id: 4,
    vehicleName: "Sedan 4 chỗ",
    routeName: "Huế → Hội An",
    type: "private-trip",
    price: 1600000,
    description: "Bao chuyến Huế - Hội An, phù hợp gia đình.",
    status: "active",
  },
];

const now = new Date();
const getOffsetISO = (minutesOffset: number) => {
  return new Date(now.getTime() - minutesOffset * 60 * 1000).toISOString();
};
const getLocalDateString = (offsetDays: number) => {
  const d = new Date(now.getTime() + offsetDays * 24 * 60 * 60 * 1000);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const bookings: Booking[] = [
  {
    id: 1,
    code: "BC-20260602-001",
    customerName: "Nguyễn Minh Anh",
    phone: "0905123456",
    routeName: "Huế → Đà Nẵng",
    travelDate: getLocalDateString(0),
    travelTime: "08:30",
    pickupAddress: "12 Hùng Vương, Huế",
    dropoffAddress: "Sân bay Đà Nẵng",
    passengerCount: 2,
    totalPrice: 400000,
    status: "new",
    internalNote: "Khách cần đón đúng giờ.",
    createdAt: getOffsetISO(45), // 45 phút trước
  },
  {
    id: 2,
    code: "BC-20260602-002",
    customerName: "Trần Hoàng Nam",
    phone: "0911888999",
    routeName: "Đà Nẵng → Hội An",
    travelDate: getLocalDateString(0),
    travelTime: "09:15",
    pickupAddress: "Bến xe Đà Nẵng",
    dropoffAddress: "Phố cổ Hội An",
    passengerCount: 1,
    totalPrice: 120000,
    status: "confirmed",
    createdAt: getOffsetISO(120), // 2 tiếng trước
  },
  {
    id: 3,
    code: "BC-20260602-003",
    customerName: "Lê Thu Hà",
    phone: "0988777666",
    routeName: "Huế → Hội An",
    travelDate: getLocalDateString(0),
    travelTime: "10:00",
    pickupAddress: "Khách sạn Century, Huế",
    dropoffAddress: "La Siesta Resort, Hội An",
    passengerCount: 4,
    totalPrice: 1600000,
    status: "completed",
    createdAt: getOffsetISO(240), // 4 tiếng trước
  },
  {
    id: 4,
    code: "BC-20260602-004",
    customerName: "Phạm Văn Đồng",
    phone: "0966555444",
    routeName: "Huế → Đà Nẵng",
    travelDate: getLocalDateString(0),
    travelTime: "13:30",
    pickupAddress: "77 Nguyễn Huệ, Huế",
    dropoffAddress: "Cầu Rồng, Đà Nẵng",
    passengerCount: 1,
    totalPrice: 200000,
    status: "new",
    createdAt: getOffsetISO(10), // 10 phút trước
  },
  {
    id: 5,
    code: "BC-20260602-005",
    customerName: "Hoàng Thị Loan",
    phone: "0977444333",
    routeName: "Đà Nẵng → Hội An",
    travelDate: getLocalDateString(1),
    travelTime: "14:15",
    pickupAddress: "Lotte Mart Đà Nẵng",
    dropoffAddress: "An Bàng Beach, Hội An",
    passengerCount: 2,
    totalPrice: 240000,
    status: "new",
    createdAt: getOffsetISO(35), // 35 phút trước
  },
  {
    id: 6,
    code: "BC-20260602-006",
    customerName: "Vũ Văn Thanh",
    phone: "0905999888",
    routeName: "Huế → Hội An",
    travelDate: getLocalDateString(1),
    travelTime: "15:00",
    pickupAddress: "Ga Huế",
    dropoffAddress: "Vinpearl Nam Hội An",
    passengerCount: 3,
    totalPrice: 1200000,
    status: "new",
    createdAt: getOffsetISO(8), // 8 phút trước
  },
  {
    id: 7,
    code: "BC-20260602-007",
    customerName: "Đỗ Hùng Dũng",
    phone: "0914111222",
    routeName: "Huế → Đà Nẵng",
    travelDate: getLocalDateString(2),
    travelTime: "07:30",
    pickupAddress: "Bệnh viện Trung ương Huế",
    dropoffAddress: "Hải Châu, Đà Nẵng",
    passengerCount: 2,
    totalPrice: 400000,
    status: "new",
    createdAt: getOffsetISO(12), // 12 phút trước
  },
  {
    id: 8,
    code: "BC-20260602-008",
    customerName: "Nguyễn Quang Hải",
    phone: "0915333444",
    routeName: "Đà Nẵng → Hội An",
    travelDate: getLocalDateString(2),
    travelTime: "09:00",
    pickupAddress: "Sơn Trà, Đà Nẵng",
    dropoffAddress: "Cửa Đại, Hội An",
    passengerCount: 1,
    totalPrice: 120000,
    status: "new",
    createdAt: getOffsetISO(5), // 5 phút trước
  },
  {
    id: 9,
    code: "BC-20260602-009",
    customerName: "Phan Văn Đức",
    phone: "0935222111",
    routeName: "Huế → Đà Nẵng",
    travelDate: getLocalDateString(3),
    travelTime: "10:30",
    pickupAddress: "Vỹ Dạ, Huế",
    dropoffAddress: "Ngũ Hành Sơn, Đà Nẵng",
    passengerCount: 2,
    totalPrice: 400000,
    status: "new",
    createdAt: getOffsetISO(3), // 3 phút trước
  },
  {
    id: 10,
    code: "BC-20260602-010",
    customerName: "Quế Ngọc Hải",
    phone: "0944666777",
    routeName: "Huế → Hội An",
    travelDate: getLocalDateString(3),
    travelTime: "16:00",
    pickupAddress: "An Cựu City, Huế",
    dropoffAddress: "Phố cổ Hội An",
    passengerCount: 1,
    totalPrice: 1600000,
    status: "new",
    createdAt: getOffsetISO(1), // 1 phút trước
  },
  {
    id: 11,
    code: "BC-20260601-011",
    customerName: "Bùi Tiến Dũng",
    phone: "0905777888",
    routeName: "Đà Nẵng → Hội An",
    travelDate: getLocalDateString(1),
    travelTime: "08:00",
    pickupAddress: "Hải Châu, Đà Nẵng",
    dropoffAddress: "Cẩm Châu, Hội An",
    passengerCount: 2,
    totalPrice: 240000,
    status: "new",
    createdAt: getOffsetISO(1440), // 24 tiếng trước
  },
  {
    id: 12,
    code: "BC-20260601-012",
    customerName: "Đoàn Văn Hậu",
    phone: "0906222333",
    routeName: "Huế → Đà Nẵng",
    travelDate: getLocalDateString(2),
    travelTime: "11:30",
    pickupAddress: "Phú Bài, Hương Thủy",
    dropoffAddress: "Liên Chiểu, Đà Nẵng",
    passengerCount: 4,
    totalPrice: 800000,
    status: "new",
    createdAt: getOffsetISO(1500),
  },
  {
    id: 13,
    code: "BC-20260601-013",
    customerName: "Trần Đình Trọng",
    phone: "0907111222",
    routeName: "Huế → Hội An",
    travelDate: getLocalDateString(3),
    travelTime: "14:00",
    pickupAddress: "Thuận An, Phú Vang",
    dropoffAddress: "Cẩm Thanh, Hội An",
    passengerCount: 2,
    totalPrice: 1600000,
    status: "new",
    createdAt: getOffsetISO(1600),
  },
  {
    id: 14,
    code: "BC-20260601-014",
    customerName: "Nguyễn Tiến Linh",
    phone: "0908333444",
    routeName: "Huế → Đà Nẵng",
    travelDate: getLocalDateString(4),
    travelTime: "17:30",
    pickupAddress: "Kim Long, Huế",
    dropoffAddress: "Thanh Khê, Đà Nẵng",
    passengerCount: 1,
    totalPrice: 200000,
    status: "new",
    createdAt: getOffsetISO(1700),
  },
  {
    id: 15,
    code: "BC-20260602-015",
    customerName: "Nguyễn Công Phượng",
    phone: "0909444555",
    routeName: "Huế → Đà Nẵng",
    travelDate: getLocalDateString(0),
    travelTime: "16:45",
    pickupAddress: "Trường Bia, Huế",
    dropoffAddress: "Hòa Khánh, Đà Nẵng",
    passengerCount: 3,
    totalPrice: 600000,
    status: "confirmed",
    createdAt: getOffsetISO(300), // 5 tiếng trước
  },
];
